src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LinkRepository::class)
 * @ORM\Table(name="links")
 */
class Link {
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\ManyToOne(targetEntity=User::class, inversedBy="links")
	 * @ORM\JoinColumn(name="fk_user_id", referencedColumnName="id", nullable=false)
	 */
	private $user;

	/**
	 * @ORM\Column(type="string", length=16)
	 */
	private $code;

	/**
	 * @ORM\Column(type="string", length=1024)
	 */
	private $destination;

	/**
	 * @ORM\Column(type="integer")
	 */
	private $ttl;

	/**
	 * @ORM\Column(type="integer")
	 */
	private $follows_count;

	public function getId(): ?int {
		return $this->id;
	}

	public function getUser(): ?User {
		return $this->user;
	}

	public function setUser(?User $user): self {
		$this->user = $user;

		return $this;
	}

	public function getCode(): ?string {
		return $this->code;
	}

	public function setCode(string $code): self {
		$this->code = $code;

		return $this;
	}

	public function getDestination(): ?string {
		return $this->destination;
	}

	public function setDestination(string $destination): self {
		$this->destination = $destination;

		return $this;
	}

	public function getTtl(): ?int {
		return $this->ttl;
	}

	public function setTtl(int $ttl): self {
		$this->ttl = $ttl;

		return $this;
	}

	public function getFollowsCount(): ?int {
		return $this->follows_count;
	}

	public function setFollowsCount(int $follows_count): self {
		$this->follows_count = $follows_count;

		return $this;
	}
}

src/Controller/LinkController.php
<?php

namespace App\Controller;

use App\Entity\Link;
use App\Form\MinifyUrlFormType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\String\ByteString;

/**
 * This controller is responsible for Link browsing, viewing, generating and handling
 */
class LinkController extends AbstractController {
	private $security;

	public function __construct(Security $security) {
		$this->security = $security;
	}

	/**
	 * Browse user's links
	 */
	public function browse(): Response {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		return $this->render('link/browse.html.twig', [
			'links' => $this->security->getUser()->getLinks()
		]);
	}

	/**
	 * View link's information and statistics
	 */
	public function read(ManagerRegistry $doctrine, string $code): Response {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		$repository = $doctrine->getRepository(Link::class);
		$link = $repository->findOneBy(['code' => $code]);

		return $this->render('link/read.html.twig', [
			'link' => $link
		]);
	}

	/**
	 * Loads Create Link Form
	 */
	public function add(): Response {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		$link = new Link();
		$form = $this->createForm(MinifyUrlFormType::class, $link, [
			'action' => $this->generateUrl('link_create'),
			'method' => 'POST',
		]);

		return $this->renderForm('link/add.html.twig', [
			'minifyUrlForm' => $form
		]);
	}

	/**
	 * Handles Link creating
	 */
	public function create(Request $request, EntityManagerInterface $entityManager): Response {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		$link = new Link();
		$form = $this->createForm(MinifyUrlFormType::class, $link, [
			'action' => $this->generateUrl('link_create'),
			'method' => 'POST',
		]);

		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$link->setUser($this->security->getUser());
			$link->setTtl(time() + $form->get('ttl')->getData());
			$link->setCode(ByteString::fromRandom(10)->toString());
			$link->setFollowsCount(0);

			$entityManager->persist($link);
			$entityManager->flush();

			$this->addFlash('success', 'Link created!');
			return new RedirectResponse($this->generateUrl('link_browse'));
		} else {
			return $this->renderForm('link/add.html.twig', [
				'minifyUrlForm' => $form
			]);
		}
	}

	/**
	 * Handles Link deleting
	 */
	public function delete(ManagerRegistry $doctrine, string $code): Response {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		$repository = $doctrine->getRepository(Link::class);
		$link = $repository->findOneBy(['code' => $code]);
		if ($link && $link->getUser() == $this->security->getUser()) {
			$this->addFlash('success', 'Link removed!');

			$entityManager = $doctrine->getManager();
			$entityManager->remove($link);
			$entityManager->flush();

			return new RedirectResponse($this->generateUrl('link_browse'));
		} else {
			throw $this->createNotFoundException('Not found');
		}
	}

	/**
	 * Handles Link redirecting and Link follows counting
	 */
	public function follow(ManagerRegistry $doctrine, string $code): Response {
		$entityManager = $doctrine->getManager();
		$link = $entityManager->getRepository(Link::class)->findOneBy(['code' => $code]);
		// Check if link exists and if it is still valid
		if ($link && $link->getTtl() > time()) {
			// Increment follows count
			$link->setFollowsCount($link->getFollowsCount() + 1);
			$entityManager->flush();

			// Collect some other data for statistics like useragent, locations(countries), referrers, daytime etc.

			return $this->redirect($link->getDestination());
		} else {
			throw $this->createNotFoundException('Not found');
		}
	}
}

templates/link/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Link{% endblock %}

{% block body %}
	<main class="form-minify w-25 m-auto mt-5 text-center">
		{{ form_start(minifyUrlForm, {'attr': {'autocomplete': 'off'}}) }}
			<h1 class="h3 mb-3 fw-normal">Minify Url</h1>

			<div class="form-floating m-1">
				{{ form_widget(minifyUrlForm.destination, {'attr': {'class': 'form-control', 'placeholder': 'Destination', 'maxlength': '1024'}}) }}
				{{ form_label(minifyUrlForm.destination, 'Destination') }}
				<div class="form-error">
					{{ form_errors(minifyUrlForm.destination) }}
				</div>
			</div>

			<div class="form-floating m-1">
				{{ form_widget(minifyUrlForm.ttl, {'attr': {'class': 'form-control', 'placeholder': 'Time to live', 'min': '0', 'max': '2592000'}}) }}
				{{ form_label(minifyUrlForm.ttl, 'Time to live (in seconds)') }}
				<div class="form-error">
					{{ form_errors(minifyUrlForm.ttl) }}
				</div>
			</div>

			{{ form_rest(minifyUrlForm) }}

			<button class="w-100 btn btn-lg btn-primary" type="submit">Minify</button>
		{{ form_end(minifyUrlForm) }}
	</main>
{% endblock %}

templates/link/browse.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Links{% endblock %}

{% block body %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">
			{{ message }}
		</div>
	{% endfor %}

	<main class="links-list w-75 m-auto mt-5 text-center">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Link</th>
					<th scope="col">Destination</th>
					<th scope="col">Valid until</th>
					<th scope="col">Follows count</th>
					<th scope="col">Statistics</th>
					<th scope="col">Delete</th>
				</tr>
			</thead>
			<tbody>
				{% for link in links %}
					<tr>
						<th scope="row">{{ loop.index }}</th>
						<td>{{ domain ~ link.code }}</td>
						<td>{{ link.destination }}</td>
						<td>{{ link.ttl|date("H:i d.m.Y") }}</td>
						<td>{{ link.followsCount }}</td>
						<td>
							<a class="btn btn-success" href="{{ path('link_read', {code: link.code}) }}" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" role="button">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-line" viewBox="0 0 16 16">
									<path d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1V2zm1 12h2V2h-2v12zm-3 0V7H7v7h2zm-5 0v-3H2v3h2z"/>
								</svg>
							</a>
						</td>
						<td>
							<form action="{{ path('link_delete', {code: link.code}) }}" method="post">
								<button type="submit" class="btn btn-danger" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
										<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
										<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
									</svg>
								</button>
							</form>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="5">no links found</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</main>
{% endblock %}

templates/link/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Link Statistics{% endblock %}

{% block body %}
	<main class="w-25 m-4 float-left">
		<ul class="list-group list-group">
			<li class="list-group-item d-flex justify-content-between align-items-start">
				<div class="ms-2 me-auto">
					<div class="fw-bold">Link: </div>
					{{ domain ~ link.code }}
				</div>
			</li>
			<li class="list-group-item d-flex justify-content-between align-items-start">
				<div class="ms-2 me-auto">
					<div class="fw-bold">Destination: </div>
					{{ link.destination }}
				</div>
			</li>
			<li class="list-group-item d-flex justify-content-between align-items-start">
				<div class="ms-2 me-auto">
					<div class="fw-bold">Valid until: </div>
					{{ link.ttl|date("H:i d.m.Y") }}
				</div>
			</li>
		</ul>
	</main>

	<section class="w-50 m-4 float-left">
		<button type="button" class="btn btn-info btn-lg" disabled>
			Follows count <span class="badge text-bg-success">{{ link.followsCount }}</span>
		</button>
	</section>

	<section class="w-50 m-4 float-left">
		<button type="button" class="btn btn-info btn-lg" disabled>
			Follows for last 24h <span class="badge text-bg-success">{{ link.followsCount }}</span>
		</button>
	</section>

	<section class="w-50 m-4 float-left">
		<h1 class="h3 mb-3 fw-normal">Some bars</h1>
		<div class="progress m-2">
			<div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
		</div>
		<div class="progress m-2">
			<div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
		</div>
		<div class="progress m-2">
			<div class="progress-bar bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
		</div>
		<div class="progress m-2">
			<div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
		</div>
	</section>
{% endblock %}